version: '2'
services:
    mosquitto:
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - "${HOST_DATA_VOLUME}/mosquitto:/mosquitto/data"
    p5-owls:
        image: sammoorhouse/p5-owls
    grafana:
        image: grafana/grafana
        environment:
            - GF_PATHS_HOME=/data/home
            - GF_PATHS_DATA=/data
            - GF_PATHS_LOGS=/var/log/grafana
            - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
        volumes:
            - "${HOST_HOME_VOLUME}/${GRAFANA_APP_NAME}:/data/home"
            - "${HOST_DATA_VOLUME}/${GRAFANA_APP_NAME}:/data"
            - "${HOST_LOGS_VOLUME}/${GRAFANA_APP_NAME}:/var/log/grafana"
            - "${HOST_PLUGINS_VOLUME}/${GRAFANA_APP_NAME}:/var/lib/grafana/plugins"
        depends_on:
            - mosquitto
    busybox:
        image: busybox
        links:
            - p5-owls:p5-owls
            - grafana:grafana
        stdin_open: true
        tty: true
    portainer:
        image: portainer/portainer
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "${HOST_DATA_VOLUME}/${PORTAINER_APP_NAME}:/data"
    linode-3318998:
        image: sammoorhouse/linode-3318998
        ports:
            - "80:80"
        links:
            - p5-owls:p5-owls
            - grafana:grafana
