version: '2'
services:
    mosquitto:
        image: mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
    p5-owls:
        image: sammoorhouse/p5-owls
        ports:
            - "127.0.0.1:3000:80"
    grafana:
        image: grafana/grafana
        ports:
            - "127.0.0.1:3001:3000"
    linode-3318998:
        image: sammoorhouse/linode-3318998
        ports:
            - "80:80"