version: '2'
services:
    mosquitto:
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
    p5-owls:
        image: sammoorhouse/p5-owls
    grafana:
        image: grafana/grafana
    linode-3318998:
        image: sammoorhouse/linode-3318998
        network_mode: "host" 
