version: '2'
services:
    mosquitto:
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - "${HOST_DATA_VOLUME"/mosquitto:/mosquitto/data"
    p5-owls:
        image: sammoorhouse/p5-owls
    grafana:
        image: grafana/grafana
        environment:
            - GF_PATHS_DATA=/data
        volumes:
            "${HOST_DATA_VOLUME}/grafana:/data"
        depends_on:
            - mosquitto
    busybox:
        image: busybox
        links:
            - p5-owls:p5-owls
            - grafana:grafana
        stdin_open: true
        tty: true
    portainer:
        image: portainer/portainer
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "${HOST_DATA_VOLUME}/portainer:/data"
    linode-3318998:
        image: sammoorhouse/linode-3318998
        ports:
            - "80:80"
        links:
            - p5-owls:p5-owls
            - grafana:grafana
