version: '2'
services:
    mosquitto:
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - "${HOST_DATA_VOLUME}/mosquitto:/mosquitto/data"
    p5-owls:
        image: sammoorhouse/p5-owls
    grafana:
        image: grafana/grafana
        environment:
            - GF_PATHS_HOME=/data/home
            - GF_PATHS_DATA=/data
            - GF_PATHS_LOGS=/var/log/grafana
            - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
        volumes:
            - "${HOST_HOME_VOLUME}/grafana:/data/home"
            - "${HOST_DATA_VOLUME}/grafana:/data"
            - "${HOST_LOGS_VOLUME}/grafana:/var/log/grafana"
            - "${HOST_PLUGINS_VOLUME}/grafana:/var/lib/grafana/plugins"
        depends_on:
            - mosquitto
    busybox:
        image: busybox
        links:
            - p5-owls:p5-owls
            - grafana:grafana
        stdin_open: true
        tty: true
    portainer:
        image: portainer/portainer
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "${HOST_DATA_VOLUME}/portainer:/data"
    linode-3318998:
        image: sammoorhouse/linode-3318998
        ports:
            - "80:80"
        links:
            - p5-owls:p5-owls
            - grafana:grafana



1+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2017-06-29T16:02:31+0000 lvl=info msg="Path Data" logger=settings path=/data
t=2017-06-29T16:02:31+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2017-06-29T16:02:31+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins